files:
  - source: /app/src/main/res/values-en/strings.xml
    translation: /app/src/main/res/values-%android_code%/strings.xml
  - source: /fastlane/metadata/android/en-US/short_description.txt
    translation: /fastlane/translations/%locale%/short_description.txt
  - source: /fastlane/metadata/android/en-US/full_description.txt
    translation: /fastlane/translations/%locale%/full_description.txt
