name: ⬠ Validate Fastlane
on:
  workflow_dispatch:
  pull_request:

jobs:
  validateFastlane:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
